#!/usr/bin/env node
import { createPrivateKey, generateKeyPairSync, sign } from "node:crypto";
import { readFile } from "node:fs/promises";
import dgram from "node:dgram";

const NTP_EPOCH_MS = Date.UTC(1900, 0, 1);
const timeoutMs = 3_000;

function writeNtpTimestamp(buffer, offset, unixMs) { const seconds = Math.floor((unixMs - NTP_EPOCH_MS) / 1_000); const fraction = Math.floor((((unixMs - NTP_EPOCH_MS) % 1_000) / 1_000) * 2 ** 32); buffer.writeUInt32BE(seconds >>> 0, offset); buffer.writeUInt32BE(fraction >>> 0, offset + 4); }
function readNtpTimestamp(buffer, offset) { const seconds = buffer.readUInt32BE(offset); const fraction = buffer.readUInt32BE(offset + 4); return NTP_EPOCH_MS + seconds * 1_000 + Math.round((fraction / 2 ** 32) * 1_000); }
function canonicalPayload(challenge, envelope) { return JSON.stringify({ agentVersion: envelope.agentVersion, challengeId: challenge.id, challengeNonce: challenge.nonce, challengeExpiresAtMs: challenge.expiresAtMs, delayMs: envelope.delayMs, offsetMs: envelope.offsetMs, protocolVersion: envelope.protocolVersion, sampledAtMs: envelope.sampledAtMs, sourceId: envelope.sourceId, stratum: envelope.stratum, uncertaintyMs: envelope.uncertaintyMs }); }

function measureNtp(host) { return new Promise((resolve, reject) => { const socket = dgram.createSocket("udp4"); const packet = Buffer.alloc(48); packet[0] = 0x23; const sentAt = Date.now(); writeNtpTimestamp(packet, 40, sentAt); const timeout = setTimeout(() => { socket.close(); reject(new Error("NTP UDP timeout")); }, timeoutMs); socket.once("error", error => { clearTimeout(timeout); socket.close(); reject(error); }); socket.once("message", response => { const receivedAt = Date.now(); clearTimeout(timeout); socket.close(); if (response.length < 48) return reject(new Error("Invalid NTP response")); const t2 = readNtpTimestamp(response, 32); const t3 = readNtpTimestamp(response, 40); const delayMs = Math.max(0, (receivedAt - sentAt) - (t3 - t2)); const offsetMs = ((t2 - sentAt) + (t3 - receivedAt)) / 2; resolve({ offsetMs, delayMs, uncertaintyMs: Math.max(1, delayMs / 2), stratum: response[1] }); }); socket.send(packet, 123, host); }); }

async function trpcCall(baseUrl, procedure, input) { const response = await fetch(`${baseUrl.replace(/\/$/, "")}/api/trpc/${procedure}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ json: input }) }); if (!response.ok) throw new Error(`ChronoMesh API returned ${response.status}`); const payload = await response.json(); const data = payload?.result?.data?.json ?? payload?.[0]?.result?.data?.json; if (!data) throw new Error("ChronoMesh API response was malformed"); return data; }

function printKeyPair() { const { publicKey, privateKey } = generateKeyPairSync("ed25519"); const publicDer = publicKey.export({ type: "spki", format: "der" }); const privateDer = privateKey.export({ type: "pkcs8", format: "der" }); console.log(JSON.stringify({ publicKeyBase64: publicDer.subarray(-32).toString("base64"), privateKeyPkcs8Base64: privateDer.toString("base64") }, null, 2)); }

async function attest(configPath) { const config = JSON.parse(await readFile(configPath, "utf8")); const credential = config.enrollmentCredential; if (!credential || !config.installationId || !config.sourceId || !config.sourceHost) throw new Error("Incomplete agent configuration"); const challenge = await trpcCall(config.apiBaseUrl, "chronomesh.requestAgentAttestationChallenge", { installationId: config.installationId, enrollmentCredential: credential, sourceId: config.sourceId }); const measurement = await measureNtp(config.sourceHost); const unsigned = { protocolVersion: 1, challengeId: challenge.id, sourceId: config.sourceId, sampledAtMs: Date.now(), offsetMs: measurement.offsetMs, delayMs: measurement.delayMs, uncertaintyMs: measurement.uncertaintyMs, stratum: measurement.stratum || null, agentVersion: config.agentVersion || "0.1.0" }; const key = createPrivateKey({ key: Buffer.from(config.privateKeyPkcs8Base64, "base64"), type: "pkcs8", format: "der" }); const signatureBase64 = sign(null, Buffer.from(canonicalPayload(challenge, unsigned)), key).toString("base64"); const accepted = await trpcCall(config.apiBaseUrl, "chronomesh.submitAgentAttestation", { installationId: config.installationId, enrollmentCredential: credential, nonce: challenge.nonce, envelope: { ...unsigned, signatureBase64 } }); console.log(JSON.stringify({ accepted, sampledAtMs: unsigned.sampledAtMs, delayMs: unsigned.delayMs, uncertaintyMs: unsigned.uncertaintyMs }, null, 2)); }

const [command, configPath] = process.argv.slice(2);
if (command === "keygen") printKeyPair(); else if (command === "attest" && configPath) attest(configPath).catch(error => { console.error(`ChronoMesh agent: ${error.message}`); process.exitCode = 1; }); else console.error("Usage: node agent.mjs keygen | node agent.mjs attest ./config.json");
