import { ArrowLeft, BookOpen, Clock3, EyeOff, Network, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { CORRECTED_TIME_CAVEAT, FRESHNESS_COPY, coverageExplanation } from "@shared/chronomeshEditorial";

function MethodCard({ icon: Icon, title, children }: { icon: typeof Clock3; title: string; children: React.ReactNode }) {
  return <section className="border border-[#a3e635]/20 bg-black/25 p-5"><div className="flex items-center gap-2 text-[#a3e635]"><Icon className="h-4 w-4" /><h2 className="numeric text-xs font-bold tracking-[.16em]">{title}</h2></div><div className="mt-3 text-sm leading-relaxed text-[#c4c4c9]">{children}</div></section>;
}

export default function Methodology() {
  const partialCoverage = coverageExplanation(60, 60);
  return <main className="min-h-screen bg-[#090a0a] px-4 py-6 text-[#e4e4e7] sm:px-6 lg:px-10"><div className="mx-auto max-w-5xl"><header className="border border-[#a3e635]/25 bg-[#0d0f0d] p-5 sm:p-7"><Link href="/sync" className="inline-flex items-center gap-2 text-xs text-[#a1a1aa] hover:text-[#a3e635] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#a3e635]"><ArrowLeft className="h-3.5 w-3.5" />BACK TO SYNCHRONIZE</Link><div className="mt-6 flex items-center gap-2 text-[#a3e635]"><BookOpen className="h-4 w-4" /><span className="numeric text-[11px] font-bold tracking-[.2em]">METHODOLOGY / SINGLE SOURCE OF TRUTH</span></div><h1 className="mt-3 text-3xl font-semibold tracking-tight text-[#f4f4f5] sm:text-5xl">What ChronoMesh measures—and what it does not claim.</h1><p className="mt-4 max-w-3xl text-sm leading-relaxed text-[#c4c4c9]">This page is the canonical explanation for the dashboard’s corrected-time estimate, uncertainty, community-source evidence, freshness, and privacy boundaries. Other in-product explanations intentionally link here rather than reinterpret these terms.</p></header>

    <div className="mt-5 grid gap-5 lg:grid-cols-2"><MethodCard icon={Clock3} title="CORRECTED TIME IS AN ESTIMATE"><p>ChronoMesh uses a four-timestamp exchange to estimate local clock offset and network delay. The dashboard presents corrected UTC alongside a stated uncertainty envelope. {CORRECTED_TIME_CAVEAT}</p><p className="mt-3">A low delay is useful evidence, not proof of absolute accuracy. Network variation, asymmetric paths, browser timing, and the selected source cohort all limit what can be inferred from a single result.</p></MethodCard><MethodCard icon={Network} title="SOURCE CONSENSUS IS CONSERVATIVE"><p>The source mesh combines bounded measurements from curated upstream authorities and verified opt-in community sources. Eligibility, quality, reachability, diversity, and recent evidence affect the consensus; excluded or stale sources are not treated as equal evidence.</p><p className="mt-3">ChronoMesh probes only configured, verified sources. It does not conduct internet-wide scanning or claim that every reachable clock should be trusted.</p></MethodCard><MethodCard icon={ShieldCheck} title="SIGNED COMMUNITY EVIDENCE"><p>A contributor-controlled agent generates an Ed25519 key on the operator device. A one-time server challenge is signed with the local private key immediately after a bounded source measurement. Challenges expire after ten minutes and cannot be replayed after successful use.</p><p className="mt-3">Attestation freshness is limited to 24 hours. A fresh attestation is evidence of recent, signed reporting—not a permanent availability or accuracy guarantee.</p></MethodCard><MethodCard icon={EyeOff} title="PRIVACY AND AGGREGATION"><p>Peer rooms use anonymous identities. Public source and observability views are aggregate-only: they do not expose raw peer identity, IP address, non-consented hardware detail, private description, hidden hostname, enrollment credential, or private signing key.</p><p className="mt-3">Long history is represented with durable aggregate buckets. For incomplete history, the dashboard shows the coverage ratio, plain-language limitation, and a safe next action instead of inventing continuity.</p></MethodCard></div>

    <section className="mt-5 border border-amber-300/30 bg-amber-300/[.05] p-5"><h2 className="numeric text-xs font-bold tracking-[.16em] text-amber-200">HOW TO READ FRESHNESS AND COVERAGE</h2><div className="mt-3 grid gap-4 text-sm leading-relaxed text-[#d4d4d8] md:grid-cols-2"><p><span className="text-[#a3e635]">Live estimate:</span> {FRESHNESS_COPY.live.implication} {FRESHNESS_COPY.live.nextAction}</p><p><span className="text-amber-200">Partial coverage:</span> {partialCoverage.implication} {partialCoverage.nextAction}</p></div></section>

    <section className="mt-5 border border-[#a3e635]/20 p-5"><h2 className="numeric text-xs font-bold tracking-[.16em] text-[#a3e635]">DECISION GUIDE</h2><p className="mt-3 text-sm leading-relaxed text-[#c4c4c9]">Use the local synchronization burst when you need a measured estimate for this device. Read uncertainty before using that estimate in a precision-sensitive decision. Use anonymous peer comparison only when it is useful to you, and use source-mesh history to understand aggregate evidence—not to identify a person or an unpublished host.</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/sync" className="border border-[#a3e635]/45 bg-[#a3e635]/10 px-3 py-2 text-xs font-semibold text-[#a3e635] hover:bg-[#a3e635]/20 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#a3e635]">RUN A SYNCHRONIZATION</Link><Link href="/contribute" className="border border-[#a3e635]/20 px-3 py-2 text-xs text-[#c4c4c9] hover:border-[#a3e635]/45 hover:text-[#a3e635] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#a3e635]">READ CONTRIBUTION WORKFLOW</Link></div></section>
  </div></main>;
}
