export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  pusherAppId: process.env.PUSHER_APP_ID ?? "",
  pusherKey: process.env.PUSHER_KEY ?? "",
  pusherSecret: process.env.PUSHER_SECRET ?? "",
  pusherCluster: process.env.PUSHER_CLUSTER ?? "",
  chronomeshRealtimeMode: (process.env.CHRONOMESH_REALTIME_MODE === "single" ? "single" : process.env.CHRONOMESH_REALTIME_MODE === "database" ? "database" : "auto") as "auto" | "database" | "single",
};
